#define CHORDAL_HOLD
#undef ONESHOT_TIMEOUT
#define ONESHOT_TIMEOUT 5000

#define PERMISSIVE_HOLD

#define QUICK_TAP_TERM 0

#define USB_SUSPEND_WAKEUP_DELAY 0
#define CAPS_LOCK_STATUS
#define SERIAL_NUMBER "EagJZ/WvbJll"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

